defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt install rsync
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run:
          command: yarn run build
      - persist_to_workspace:
                root: ~/repo
                paths:
                  - ./*

  deploy:
    <<: *defaults
    steps:
     - attach_workspace:
          at: ~/repo
      - run:
          name: deploy hugo
          command: yarn run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
